### ISSUE TITLE
Two x-Values

### ISSUE THREAD

**Issue by signalwerk** [byte-foundry/elzevir.ptf#8]
I'm right now working on a [UI-Concept](http://paramatters.signalwerk.ch/ui/) for a parametric editor like you did it with prototypo-builder. For that I'm studying your awesome work. Highly inspirational. I wonder if there is a documentation on the .ptf-Format. I get it quite good since it's verbose but I wonder for example if in https://github.com/byte-foundry/elzevir.ptf/blob/master/src/glyphs/figures/nine.coffee#L67 you really support some kind of double declaration of x-Values? Or is ist just a mistake?

**Comment by FranzPoize** [comment]
Hi Stefan! No it's just a typo. The only value that matters is the last one. It's probably something that Yannick used to do some test and forgot to remove.

Super cool stuff you're doing. Keep it up.

**Comment by signalwerk** [comment]
@FranzPoize thank you for the info!
